/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ServicoC;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.ReceptorIdProduto;
import modelo.ReceptorCliente;

/**
 *
 * @author Jéssica A Ferreira
 */
public class ServicoVisao extends javax.swing.JFrame implements ReceptorCliente, ReceptorIdProduto {

     public static Cliente cliente;
    
    
    @Override
    public void setCliente(Cliente cli) {
        this.cliente =cli;
        jTcliente.setText(cliente.getNome());
        
    }
    
    
    

    @Override
    public void setIdProduto(int id) {
        
    }

   

    /**
     * Creates new form ServicoVisao
     */
    public ServicoVisao() {
        initComponents();
        jRadio110.setActionCommand("110V");
        jRadio220.setActionCommand("220V");
        jRadioBivolt.setActionCommand("Bivolt");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGVoltagem = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLid = new javax.swing.JLabel();
        jTid = new javax.swing.JTextField();
        jLvalor = new javax.swing.JLabel();
        jTsolucao = new javax.swing.JTextField();
        jTvalor = new javax.swing.JTextField();
        jLdescricao = new javax.swing.JLabel();
        jBbuscarServicos = new javax.swing.JButton();
        jBnovo = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();
        jBsalvar2 = new javax.swing.JButton();
        jLsolucao = new javax.swing.JLabel();
        jTcliente = new javax.swing.JTextField();
        jBadicionarProduto = new javax.swing.JButton();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jTAcessorios = new javax.swing.JTextField();
        jLvoltagem1 = new javax.swing.JLabel();
        jLvoltagem = new javax.swing.JLabel();
        jLvoltagem2 = new javax.swing.JLabel();
        jRadio110 = new javax.swing.JRadioButton();
        jRadio220 = new javax.swing.JRadioButton();
        jRadioBivolt = new javax.swing.JRadioButton();
        jLcliente = new javax.swing.JLabel();
        jTdescricao = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLstatus = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Serviços");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Serviço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLid.setText("ID:");
        jPanel1.add(jLid);
        jLid.setBounds(60, 110, 30, 20);

        jTid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidActionPerformed(evt);
            }
        });
        jPanel1.add(jTid);
        jTid.setBounds(100, 110, 120, 25);

        jLvalor.setText("Valor:");
        jPanel1.add(jLvalor);
        jLvalor.setBounds(240, 110, 70, 25);

        jTsolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsolucaoActionPerformed(evt);
            }
        });
        jPanel1.add(jTsolucao);
        jTsolucao.setBounds(100, 220, 310, 25);

        jTvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTvalorActionPerformed(evt);
            }
        });
        jPanel1.add(jTvalor);
        jTvalor.setBounds(280, 110, 130, 25);

        jLdescricao.setText("Descrição:");
        jPanel1.add(jLdescricao);
        jLdescricao.setBounds(30, 70, 70, 20);

        jBbuscarServicos.setText("Buscar Serviços");
        jBbuscarServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarServicosActionPerformed(evt);
            }
        });
        jPanel1.add(jBbuscarServicos);
        jBbuscarServicos.setBounds(450, 180, 130, 40);

        jBnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icone_servicos.png"))); // NOI18N
        jBnovo.setText("Novo");
        jBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoActionPerformed(evt);
            }
        });
        jPanel1.add(jBnovo);
        jBnovo.setBounds(160, 310, 120, 50);

        jBexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Delete-icon-2.png"))); // NOI18N
        jBexcluir.setText("Excluir");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jBexcluir);
        jBexcluir.setBounds(300, 310, 120, 50);

        jBsalvar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/floppy-save-icon-23.png"))); // NOI18N
        jBsalvar2.setText("Salvar");
        jBsalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvar2ActionPerformed(evt);
            }
        });
        jPanel1.add(jBsalvar2);
        jBsalvar2.setBounds(30, 310, 120, 50);

        jLsolucao.setText("Solução:");
        jPanel1.add(jLsolucao);
        jLsolucao.setBounds(50, 220, 60, 14);

        jTcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTclienteActionPerformed(evt);
            }
        });
        jPanel1.add(jTcliente);
        jTcliente.setBounds(100, 40, 310, 25);

        jBadicionarProduto.setText("Adicionar Produto");
        jBadicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBadicionarProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jBadicionarProduto);
        jBadicionarProduto.setBounds(450, 110, 130, 40);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desktop", "Notebook", "Celular", "Tablet", "Gadgets" }));
        jPanel1.add(jComboBoxTipo);
        jComboBoxTipo.setBounds(100, 150, 71, 20);

        jTAcessorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTAcessoriosActionPerformed(evt);
            }
        });
        jPanel1.add(jTAcessorios);
        jTAcessorios.setBounds(100, 180, 310, 25);

        jLvoltagem1.setText("Acessórios:");
        jPanel1.add(jLvoltagem1);
        jLvoltagem1.setBounds(40, 180, 55, 14);

        jLvoltagem.setText("Tipo:");
        jPanel1.add(jLvoltagem);
        jLvoltagem.setBounds(60, 150, 24, 14);

        jLvoltagem2.setText("Voltagem:");
        jPanel1.add(jLvoltagem2);
        jLvoltagem2.setBounds(190, 150, 48, 20);

        bGVoltagem.add(jRadio110);
        jRadio110.setText("110V");
        jPanel1.add(jRadio110);
        jRadio110.setBounds(240, 150, 49, 23);

        bGVoltagem.add(jRadio220);
        jRadio220.setText("220V");
        jPanel1.add(jRadio220);
        jRadio220.setBounds(300, 150, 49, 23);

        bGVoltagem.add(jRadioBivolt);
        jRadioBivolt.setText("Bivolt");
        jPanel1.add(jRadioBivolt);
        jRadioBivolt.setBounds(360, 150, 51, 23);

        jLcliente.setText("Cliente:");
        jPanel1.add(jLcliente);
        jLcliente.setBounds(30, 40, 50, 14);

        jTdescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdescricaoActionPerformed(evt);
            }
        });
        jPanel1.add(jTdescricao);
        jTdescricao.setBounds(100, 70, 310, 25);

        jButton1.setText("Buscar Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 40, 130, 40);

        jLstatus.setText("Status:");
        jPanel1.add(jLstatus);
        jLstatus.setBounds(50, 260, 40, 14);

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em manutenção", "Aguardando cliente", "Entrar em contato com o cliente", "Finalizado" }));
        jComboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxStatus);
        jComboBoxStatus.setBounds(100, 260, 130, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidActionPerformed

    private void jTsolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsolucaoActionPerformed

    private void jTvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTvalorActionPerformed

    private void jBbuscarServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarServicosActionPerformed
        //new ListarClientes().setVisible(true);
    }//GEN-LAST:event_jBbuscarServicosActionPerformed

    private void jBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBnovoActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jBsalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvar2ActionPerformed

        if (cliente.getId() != 0) {
            if (bGVoltagem.getSelection() != null) {
                ArrayList<String> servico = new ArrayList<>();

                servico.add("" + cliente.getId());
                servico.add(jTdescricao.getText());
                servico.add(jTvalor.getText());
                servico.add(jComboBoxTipo.getItemAt(jComboBoxTipo.getSelectedIndex()));
                servico.add(bGVoltagem.getSelection().getActionCommand());
                servico.add(jTAcessorios.getText());
                servico.add(jTsolucao.getText());
                servico.add(jComboBoxStatus.getItemAt(jComboBoxStatus.getSelectedIndex()));

                // ServicoC sc = new ServicoC();
                //  sc.cadastrar(servico);
                new ServicoC().cadastrar(servico); // O metodo cadastrar
            } else {

                JOptionPane.showMessageDialog(this, "É necessário selecionar a voltagem!");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Cliente não selecionado!");
        }

       cliente.setId(0);  // zera o id cliente após salvar o serviço

    }//GEN-LAST:event_jBsalvar2ActionPerformed

    private void jTclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTclienteActionPerformed

    private void jBadicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBadicionarProdutoActionPerformed
        new ListarProdutos().setVisible(true);
    }//GEN-LAST:event_jBadicionarProdutoActionPerformed

    private void jTAcessoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTAcessoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAcessoriosActionPerformed

    private void jTdescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdescricaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // iDcliente = 1;
        //new ListarClientes().setVisible(true);

        new ListarClientes(this).setVisible(true);

        // iDcliente = ListarClientes.idCliente;
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServicoVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServicoVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServicoVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServicoVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServicoVisao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGVoltagem;
    private javax.swing.JButton jBadicionarProduto;
    private javax.swing.JButton jBbuscarServicos;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JButton jBnovo;
    private javax.swing.JButton jBsalvar2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLcliente;
    private javax.swing.JLabel jLdescricao;
    private javax.swing.JLabel jLid;
    private javax.swing.JLabel jLsolucao;
    private javax.swing.JLabel jLstatus;
    private javax.swing.JLabel jLvalor;
    private javax.swing.JLabel jLvoltagem;
    private javax.swing.JLabel jLvoltagem1;
    private javax.swing.JLabel jLvoltagem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadio110;
    private javax.swing.JRadioButton jRadio220;
    private javax.swing.JRadioButton jRadioBivolt;
    private javax.swing.JTextField jTAcessorios;
    private javax.swing.JTextField jTcliente;
    private javax.swing.JTextField jTdescricao;
    private javax.swing.JTextField jTid;
    private javax.swing.JTextField jTsolucao;
    private javax.swing.JTextField jTvalor;
    // End of variables declaration//GEN-END:variables

}
